# Generated by Django 5.0.14 on 2026-04-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('from_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='clubs.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='players.player')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='clubs.club')),
            ],
        ),
    ]
