# Generated by Django 5.0.14 on 2026-04-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=100)),
                ('budget', models.FloatField()),
                ('logo_url', models.URLField(max_length=500)),
                ('trophies_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club1_score', models.IntegerField()),
                ('club2_score', models.IntegerField()),
                ('date', models.DateField()),
                ('club1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='clubs.club')),
                ('club2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='clubs.club')),
            ],
        ),
    ]
