# Generated by Django 5.0.14 on 2026-04-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo_url',
            field=models.CharField(max_length=500),
        ),
    ]
