# Generated by Django 5.0.14 on 2026-04-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(choices=[('GK', 'GK'), ('CB', 'CB'), ('LB', 'LB'), ('RB', 'RB'), ('LWB', 'LWB'), ('RWB', 'RWB'), ('CDM', 'CDM'), ('CM', 'CM'), ('CAM', 'CAM'), ('LM', 'LM'), ('RM', 'RM'), ('LW', 'LW'), ('RW', 'RW'), ('ST', 'ST'), ('CF', 'CF')], max_length=3)),
                ('price', models.FloatField()),
                ('join_date', models.DateField()),
                ('image_url', models.URLField(max_length=500)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pace', models.IntegerField()),
                ('shooting', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.player')),
            ],
        ),
    ]
